### ISSUE TITLE
Is a 2024 version planned?

### ISSUE THREAD

**Issue by slrgt** [LinSoftWin/Photoshop-CC2022-Linux#127]
Any chance you will make a 2024 version?

**Comment by MiMillieuh** [comment]
Honestly I'm probable going to shut my project down, as I'm getting at the end of my studies and I'll have to pay the adobe suite full price I won't use it anymore and I don't want to use a software that I didn't paid for.

I'm also pretty sure that a lot of people use this project without having a licence (even thought I said YOU NEED to have one) and I don't want to help people to commit piracy. 

So The scripts are there, I shut down the server and since wine has improved a lot it's possible to use a vanilla build of adobe photoshop to get it working. I'll detail the instructions when I'll have some time but it won't be that automatic process you actually know.

You can see there that Photoshop has silver rating on the 2023 version https://appdb.winehq.org/objectManager.php?sClass=application&iId=17

Sorry for the inconvenience.

**Comment by BrycensRanch** [comment]
> Honestly I'm probable going to shut my project down, as I'm getting at the end of my studies and I'll have to pay the adobe suite full price I won't use it anymore and I don't want to use a software that I didn't paid for.
> 
> I'm also pretty sure that a lot of people use this project without having a licence (even thought I said YOU NEED to have one) and I don't want to help people to commit piracy.
> 
> So The scripts are there, I shut down the server and since wine has improved a lot it's possible to use a vanilla build of adobe photoshop to get it working. I'll detail the instructions when I'll have some time but it won't be that automatic process you actually know.
> 
> You can see there that Photoshop has silver rating on the 2023 version https://appdb.winehq.org/objectManager.php?sClass=application&iId=17
> 
> Sorry for the inconvenience.

Hey, I know open-source development is usually thankless work, but, I'd like to thank you for all the work you've done for the community. Previously, I thought Photopshop running in Wine was next to impossible on Linux. You've done great already for how long you kept this up. :heart:
